name: i_am_amazing
description: My second flutter app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: lib/fonts/RobotoMono-Medium.ttf
    - family: Source Sans Pro
      fonts:
        - asset: lib/fonts/SourceSansPro-Regular.ttf


  uses-material-design: true

  assets:
    - lib/images/devanshi0.jpg





